name: Scheduled Sync

on:
  schedule:
    # 修改为每小时的第 25 分钟执行，避开整点拥堵，提高触发成功率
    - cron: '25 * * * *'
  workflow_dispatch: # 保持手动触发按钮，方便测试

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync upstream changes
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/judy-gotv/iptv.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
